# Generated by Django 5.1 on 2025-03-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_registration_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
