# Generated by Django 5.1 on 2025-03-24 19:56

import registration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_registration_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='approval_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='datacontroller',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/', validators=[registration.models.validate_document_file]),
        ),
        migrations.AlterField(
            model_name='registration',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='Pending', max_length=10),
        ),
    ]
