# Generated by Django 5.1 on 2025-04-04 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_databreach'),
    ]

    operations = [
        migrations.RenameField(
            model_name='databreach',
            old_name='organization',
            new_name='organization_name',
        ),
        migrations.AddField(
            model_name='databreach',
            name='date_reported',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 4, 4, 18, 47, 31, 285879, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='databreach',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='databreach',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved')], default='pending', max_length=20),
        ),
    ]
