# Generated by Django 5.1 on 2025-04-07 20:20

import registration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_databreach_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='databreach',
            name='actions_taken',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databreach',
            name='supporting_documents',
            field=models.FileField(blank=True, null=True, upload_to='documents/', validators=[registration.models.validate_document_file]),
        ),
        migrations.AlterField(
            model_name='registration',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/', validators=[registration.models.validate_document_file]),
        ),
        migrations.DeleteModel(
            name='DataBreachReport',
        ),
    ]
