# Generated by Django 5.1 on 2025-04-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_databreach_actions_taken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='databreach',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
