# Generated by Django 5.1 on 2025-04-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_databreach_email_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='payment_verified',
            field=models.BooleanField(default=False),
        ),
    ]
