# Generated by Django 5.1 on 2025-05-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_registration_payment_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='databreach',
            name='cause',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databreach',
            name='recommendations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databreach',
            name='resolution_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
