# Generated by Django 5.1 on 2025-05-18 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_databreach_cause_databreach_recommendations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
